### ISSUE TITLE
suggestion: copy video URL to clipboard

### ISSUE THREAD

**Issue by elig0n** [darkhz/invidtui#13]
this can be useful for opening a video in browser, downloading it, sharing it, etc...
preferably or separately with current time

**Comment by darkhz** [comment]
This can be somewhat tedious to implement, due to the following reasons:
- Since invidtui is cross-platform, a unified method to access the clipboard should be available. There are some libraries that provide such functionality, but will require more dependencies to be installed (and these libraries don't support Wayland yet I think).
- Within Linux itself, there is both X11, Wayland and XWayland. Their clipboard-related behaviors and methods to access them vary.

For now, I think you can save your playlist in invidtui to a m3u8 file, and then access the urls from there. If you have any suggestions to tackle this issue, let me know.

**Comment by ghost** [comment]
And something similar to the behavior of [newsboat](https://github.com/newsboat/newsboat) macros? In newsboat when I click ",," in a feed it opens directly in my browser.

**Comment by elig0n** [comment]
For one, a general video/playlist entry information popup where the video URL/id is shown (among other things) can tackle this, by letting the user copy it with the mouse/tmux selection.

I also found that I can copy the URL off mpv (via an extension script) and although that is a direct video file URL the youtube ID is part of URL queries

**Comment by darkhz** [comment]
@elig0n can you show the extension script used to copy the URL off mpv? It would be useful to know how the implementation works. And yes, the popup method is a good suggestion, I'll implement that.

**Comment by elig0n** [comment]
> @elig0n can you show the extension script used to copy the URL off mpv? It would be useful to know how the implementation works. And yes, the popup method is a good suggestion, I'll implement that.

I use https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SmartCopyPaste.lua which supports mac linux and windows and many customization and copy/paste options but there are others as well
